// HWANG GEUM (황금모피) - Official Lookbook Data
// Section: HWANG GUM HERITAGE LOOKBOOK
window.HWANG_GEUM_LOOKBOOK = [
  // ==========================================
  // COAT & JACKET
  // ==========================================
  {
    id: "look-01",
    lookNumber: "LOOK 01",
    titleKo: "블랙그라마 가로 티어 밍크 자켓",
    titleEn: "Blackglama® Horizontal Tier Mink Jacket",
    categoryKey: "jacket-coat",
    categoryLabel: "Coat & Jacket",
    peltGrade: "North American Blackglama® Mink (Full Pelt)",
    color: "Deep Black Noir",
    image: "assets/images/lookbook/lookbook_07.jpg",
    storeUrl: "https://smartstore.naver.com/goldfur_kr/products/12606360112",
    description: "북미 최상위 블랙그라마 원피를 가로 스트라이프 티어 공법으로 조립하여 모피 본연의 풍성한 볼륨감과 입체적인 음영을 선사하는 시그니처 자켓입니다. 손끝에 걸리지 않는 특수 미싱 봉제로 완성했습니다."
  },
  {
    id: "look-02",
    lookNumber: "LOOK 02",
    titleKo: "시그니처 후드 롱 통밍크 코트",
    titleEn: "Hooded Long Full-Pelt Mink Coat",
    categoryKey: "jacket-coat",
    categoryLabel: "Coat & Jacket",
    peltGrade: "Premium Natural Female Mink (Full Pelt)",
    color: "Rich Mahogany Sable",
    image: "assets/images/lookbook/lookbook_20.jpg",
    storeUrl: "https://smartstore.naver.com/goldfur_kr/category/d7adb89b9e1742a58cf32afdde4a6591?cp=1",
    description: "얼굴선을 부드럽게 감싸는 후드 디테일과 발목 위까지 우아하게 떨어지는 풀렝스 실루엣. 깃털처럼 가벼운 판장 공법을 적용해 롱코트임에도 어깨 결림 없는 극상의 편안함을 선사합니다."
  },
  {
    id: "look-03",
    lookNumber: "LOOK 03",
    titleKo: "아키텍처럴 후드 맥시 실루엣",
    titleEn: "Architectural Hooded Maxi Silhouette",
    categoryKey: "jacket-coat",
    categoryLabel: "Coat & Jacket",
    peltGrade: "SAGA Royal Female Mink (Full Pelt)",
    color: "Deep Espresso Dark",
    image: "assets/images/lookbook/lookbook_22.jpg",
    storeUrl: "https://smartstore.naver.com/goldfur_kr/category/d7adb89b9e1742a58cf32afdde4a6591?cp=1",
    description: "몸을 포근하게 감싸는 볼륨감과 절제된 테일러드 핏의 조화. 35년 부부 장인이 직접 수작업으로 안감 라이닝을 시침하여 걸을 때마다 흐트러짐 없는 드라마틱한 동세를 완성합니다."
  },
  {
    id: "look-04",
    lookNumber: "LOOK 04",
    titleKo: "파스텔 토프 스탠카라 통밍크 자켓",
    titleEn: "Pastel Taupe Stand Collar Mink Jacket",
    categoryKey: "jacket-coat",
    categoryLabel: "Coat & Jacket",
    peltGrade: "Natural Pastel Mink (Full Pelt)",
    color: "Soft Taupe Beige",
    image: "assets/images/lookbook/lookbook_11.jpg",
    storeUrl: "https://smartstore.naver.com/goldfur_kr/category/d7adb89b9e1742a58cf32afdde4a6591?cp=1",
    description: "목선을 단아하게 세워주는 스탠드 카라 디자인에 따뜻하고 부드러운 파스텔 톤을 더했습니다. 캐주얼 룩부터 격식 있는 이브닝 룩까지 다채롭게 연출 가능한 타임리스 피스입니다."
  },
  {
    id: "look-05",
    lookNumber: "LOOK 05",
    titleKo: "테일러드 미니멀 밍크 블루종",
    titleEn: "Tailored Minimalist Mink Blouson",
    categoryKey: "jacket-coat",
    categoryLabel: "Coat & Jacket",
    peltGrade: "Premium Natural Mink (Full Pelt)",
    color: "Muted Warm Greige",
    image: "assets/images/lookbook/lookbook_13.jpg",
    storeUrl: "https://smartstore.naver.com/goldfur_kr/category/d7adb89b9e1742a58cf32afdde4a6591?cp=1",
    description: "불필요한 장식을 배제하고 모피 본연의 결감과 자연광의 은은한 반사만을 극대화한 미니멀 블루종. 촘촘한 언더퍼가 찬바람을 완벽하게 차단합니다."
  },
  {
    id: "look-06",
    lookNumber: "LOOK 06",
    titleKo: "마호가니 라운드넥 통밍크 자켓",
    titleEn: "Mahogany Round Neck Mink Jacket",
    categoryKey: "jacket-coat",
    categoryLabel: "Coat & Jacket",
    peltGrade: "Blackglama® Female Mink (Full Pelt)",
    color: "Mahogany Dark Brown",
    image: "assets/images/lookbook/lookbook_44.jpg",
    storeUrl: "https://smartstore.naver.com/goldfur_kr/category/d7adb89b9e1742a58cf32afdde4a6591?cp=1",
    description: "목선을 유려하게 드러내는 깔끔한 라운드넥 컷과 딥 마호가니의 클래식한 조화. 이너웨어와 스카프 매치가 자유로우며 일상 속 가벼운 외출에도 높은 활용도를 자랑합니다."
  },
  {
    id: "look-07",
    lookNumber: "LOOK 07",
    titleKo: "딥 노아 클래식 밍크 코트",
    titleEn: "Deep Noir Classic Mink Coat",
    categoryKey: "jacket-coat",
    categoryLabel: "Coat & Jacket",
    peltGrade: "North American Blackglama® (Full Pelt)",
    color: "Pure Black Noir",
    image: "assets/images/lookbook/lookbook_06.jpg",
    storeUrl: "https://smartstore.naver.com/goldfur_kr/category/d7adb89b9e1742a58cf32afdde4a6591?cp=1",
    description: "가장 깊은 블랙 색상과 빽빽한 단모 밀도를 자랑하는 북미 블랙그라마 원피만 엄선하여 제작한 정통 클래식 밍크 코트입니다. 대를 이어 물려줄 수 있는 높은 소장 가치를 지닙니다."
  },
  {
    id: "look-08",
    lookNumber: "LOOK 08",
    titleKo: "스탠드 카라 쁘띠 하프 코트",
    titleEn: "Stand Collar Petite Half Coat",
    categoryKey: "jacket-coat",
    categoryLabel: "Coat & Jacket",
    peltGrade: "SAGA Royal Female Mink (Full Pelt)",
    color: "Midnight Black",
    image: "assets/images/lookbook/lookbook_08.jpg",
    storeUrl: "https://smartstore.naver.com/goldfur_kr/category/d7adb89b9e1742a58cf32afdde4a6591?cp=1",
    description: "한국인 여성의 평균 체형을 고려한 최적의 힙 라인 하프 기장감. 활동성이 우수하며 운전 시에도 편안하게 착용할 수 있는 실용적인 럭셔리 하프 코트입니다."
  },
  {
    id: "look-09",
    lookNumber: "LOOK 09",
    titleKo: "체스트넛 스탠카라 통밍크 자켓",
    titleEn: "Chestnut Stand Collar Mink Jacket",
    categoryKey: "jacket-coat",
    categoryLabel: "Coat & Jacket",
    peltGrade: "Natural Demi-Buff Mink (Full Pelt)",
    color: "Warm Chestnut Brown",
    image: "assets/images/lookbook/lookbook_10.jpg",
    storeUrl: "https://smartstore.naver.com/goldfur_kr/category/d7adb89b9e1742a58cf32afdde4a6591?cp=1",
    description: "부드러운 밤색 톤의 따뜻한 광택이 피부 톤을 화사하게 밝혀줍니다. 정교한 V자 대칭 패턴 재단으로 입었을 때 어깨선이 들뜨지 않고 자연스럽게 감깁니다."
  },
  {
    id: "look-10",
    lookNumber: "LOOK 10",
    titleKo: "블랙그라마 집업 아틀리에 블루종",
    titleEn: "Blackglama® Zip Atelier Blouson",
    categoryKey: "jacket-coat",
    categoryLabel: "Coat & Jacket",
    peltGrade: "North American Blackglama® (Full Pelt)",
    color: "Ebony Black",
    image: "assets/images/lookbook/lookbook_12.jpg",
    storeUrl: "https://smartstore.naver.com/goldfur_kr/category/d7adb89b9e1742a58cf32afdde4a6591?cp=1",
    description: "정교한 투웨이 지퍼 디테일과 스포티한 블루종 실루엣의 만남. 젊고 감각적인 무드로 일상 속에서 가장 손이 자주 가는 모피 자켓입니다."
  },
  {
    id: "look-11",
    lookNumber: "LOOK 11",
    titleKo: "사토리얼 블랙 통밍크 자켓",
    titleEn: "Sartorial Black Mink Jacket",
    categoryKey: "jacket-coat",
    categoryLabel: "Coat & Jacket",
    peltGrade: "Premium Blackglama® Mink (Full Pelt)",
    color: "Sartorial Black",
    image: "assets/images/lookbook/lookbook_14.jpg",
    storeUrl: "https://smartstore.naver.com/goldfur_kr/category/d7adb89b9e1742a58cf32afdde4a6591?cp=1",
    description: "맞춤 테일러드 수트의 정교한 어깨선과 암홀 곡선을 모피에 이식했습니다. 부해 보이지 않는 날렵한 실루엣을 완성했습니다."
  },
  {
    id: "look-12",
    lookNumber: "LOOK 12",
    titleKo: "로열 헤리티지 블랙그라마 코트",
    titleEn: "Royal Heritage Blackglama® Coat",
    categoryKey: "jacket-coat",
    categoryLabel: "Coat & Jacket",
    peltGrade: "Blackglama® Top Lot Female Mink",
    color: "Imperial Black",
    image: "assets/images/lookbook/lookbook_15.jpg",
    storeUrl: "https://smartstore.naver.com/goldfur_kr/category/d7adb89b9e1742a58cf32afdde4a6591?cp=1",
    description: "경매 최고 등급 탑롯(Top Lot) 원피만으로 제작되어 벨벳처럼 조밀하고 부드러운 감촉을 자랑합니다. 황금모피 35년 기술의 집약체입니다."
  },
  {
    id: "look-13",
    lookNumber: "LOOK 13",
    titleKo: "토프 호라이즌 티어드 코트",
    titleEn: "Taupe Horizon Tiered Coat",
    categoryKey: "jacket-coat",
    categoryLabel: "Coat & Jacket",
    peltGrade: "SAGA Royal Female Mink (Full Pelt)",
    color: "Muted Taupe Gray",
    image: "assets/images/lookbook/lookbook_18.jpg",
    storeUrl: "https://smartstore.naver.com/goldfur_kr/category/d7adb89b9e1742a58cf32afdde4a6591?cp=1",
    description: "가로 방향의 정교한 밴딩 봉제로 모피 특유의 무게를 분산시키고 현대적인 건축적 리듬감을 부여한 세련된 티어드 코트입니다."
  },
  {
    id: "look-14",
    lookNumber: "LOOK 14",
    titleKo: "미드나잇 슬림 실루엣 밍크 코트",
    titleEn: "Midnight Slim Silhouette Coat",
    categoryKey: "jacket-coat",
    categoryLabel: "Coat & Jacket",
    peltGrade: "Premium Black Female Mink (Full Pelt)",
    color: "Midnight Noir",
    image: "assets/images/lookbook/lookbook_19.jpg",
    storeUrl: "https://smartstore.naver.com/goldfur_kr/category/d7adb89b9e1742a58cf32afdde4a6591?cp=1",
    description: "허리 라인을 과하지 않게 자연스럽게 잡아주어 슬림하고 기품 있는 연출이 가능한 롱 실루엣 코트입니다."
  },
  {
    id: "look-15",
    lookNumber: "LOOK 15",
    titleKo: "팔로미노 골든 밍크 자켓",
    titleEn: "Palomino Golden Mink Jacket",
    categoryKey: "jacket-coat",
    categoryLabel: "Coat & Jacket",
    peltGrade: "Natural Rare Palomino Mink (Full Pelt)",
    color: "Golden Palomino",
    image: "assets/images/lookbook/lookbook_21.jpg",
    storeUrl: "https://smartstore.naver.com/goldfur_kr/category/d7adb89b9e1742a58cf32afdde4a6591?cp=1",
    description: "인위적인 염색이 아닌 천연 희귀 팔로미노 원피 본연의 은은한 골드빛. 입는 순간 얼굴 전체에 화사한 아우라를 더해줍니다."
  },
  {
    id: "look-16",
    lookNumber: "LOOK 16",
    titleKo: "데미버프 클래식 밍크 코트",
    titleEn: "Demi-Buff Classic Mink Coat",
    categoryKey: "jacket-coat",
    categoryLabel: "Coat & Jacket",
    peltGrade: "Natural Demi-Buff Female Mink",
    color: "Rich Bronze Demi",
    image: "assets/images/lookbook/lookbook_23.jpg",
    storeUrl: "https://smartstore.naver.com/goldfur_kr/category/d7adb89b9e1742a58cf32afdde4a6591?cp=1",
    description: "자연 그대로의 브론즈 브라운 컬러 톤이 고급스러운 깊이감을 연출합니다. 유행을 타지 않는 영원한 타임리스 디자인입니다."
  },
  {
    id: "look-17",
    lookNumber: "LOOK 17",
    titleKo: "플레어 슬리브 후드 밍크 코트",
    titleEn: "Flared Sleeve Hooded Mink Coat",
    categoryKey: "jacket-coat",
    categoryLabel: "Coat & Jacket",
    peltGrade: "Premium Dark Mink (Full Pelt)",
    color: "Deep Espresso",
    image: "assets/images/lookbook/lookbook_34.jpg",
    storeUrl: "https://smartstore.naver.com/goldfur_kr/category/d7adb89b9e1742a58cf32afdde4a6591?cp=1",
    description: "소매 끝으로 갈수록 은은하게 넓어지는 7부 와이드 슬리브와 풍성한 후드의 조화. 이너웨어 니트와의 레이어드가 돋보이는 모던 럭셔리 실루엣입니다."
  },
  {
    id: "look-18",
    lookNumber: "LOOK 18",
    titleKo: "파스텔 카멜 테일러드 밍크 자켓",
    titleEn: "Pastel Camel Tailored Mink Jacket",
    categoryKey: "jacket-coat",
    categoryLabel: "Coat & Jacket",
    peltGrade: "Natural Pastel Mink (Full Pelt)",
    color: "Warm Camel",
    image: "assets/images/lookbook/lookbook_36.jpg",
    storeUrl: "https://smartstore.naver.com/goldfur_kr/category/d7adb89b9e1742a58cf32afdde4a6591?cp=1",
    description: "고급스러운 카멜 베이지 컬러가 선사하는 온화한 기품. 부드러운 가죽 판장 가공으로 가볍고 자연스럽게 드레이프됩니다."
  },
  {
    id: "look-19",
    lookNumber: "LOOK 19",
    titleKo: "펄 애쉬 테일러드 밍크 자켓",
    titleEn: "Pearl Ash Tailored Mink Jacket",
    categoryKey: "jacket-coat",
    categoryLabel: "Coat & Jacket",
    peltGrade: "SAGA Royal Pearl Mink (Full Pelt)",
    color: "Pearl Ash Gray",
    image: "assets/images/lookbook/lookbook_37.jpg",
    storeUrl: "https://smartstore.naver.com/goldfur_kr/category/d7adb89b9e1742a58cf32afdde4a6591?cp=1",
    description: "맑고 깨끗한 진줏빛 회색 톤으로 현대적이고 도회적인 세련미를 자아내는 스탠카라 테일러드 자켓입니다."
  },
  {
    id: "look-20",
    lookNumber: "LOOK 20",
    titleKo: "미드나잇 블루 밍크 하프 코트",
    titleEn: "Midnight Blue Mink Half Coat",
    categoryKey: "jacket-coat",
    categoryLabel: "Coat & Jacket",
    peltGrade: "Premium Female Mink (Full Pelt)",
    color: "Midnight Blue Noir",
    image: "assets/images/lookbook/lookbook_38.jpg",
    storeUrl: "https://smartstore.naver.com/goldfur_kr/category/d7adb89b9e1742a58cf32afdde4a6591?cp=1",
    description: "빛의 각도에 따라 은은한 네이비 블루빛이 감도는 특별한 컬러링. 세련된 도시 여성의 감성을 담았습니다."
  },
  {
    id: "look-21",
    lookNumber: "LOOK 21",
    titleKo: "슬레이트 사파이어 밍크 코트",
    titleEn: "Slate Sapphire Mink Coat",
    categoryKey: "jacket-coat",
    categoryLabel: "Coat & Jacket",
    peltGrade: "Natural Sapphire Mink (Full Pelt)",
    color: "Slate Sapphire",
    image: "assets/images/lookbook/lookbook_39.jpg",
    storeUrl: "https://smartstore.naver.com/goldfur_kr/category/d7adb89b9e1742a58cf32afdde4a6591?cp=1",
    description: "북유럽 천연 사파이어 밍크의 신비로운 블루그레이 톤. 극도로 촘촘한 언더퍼가 완성하는 소프트한 터치감이 일품입니다."
  },
  {
    id: "look-22",
    lookNumber: "LOOK 22",
    titleKo: "실버블루 테일러드 모피 코트",
    titleEn: "Silver Blue Tailored Fur Coat",
    categoryKey: "jacket-coat",
    categoryLabel: "Coat & Jacket",
    peltGrade: "SAGA Royal Silver Blue Mink",
    color: "Silver Blue Mist",
    image: "assets/images/lookbook/lookbook_40.jpg",
    storeUrl: "https://smartstore.naver.com/goldfur_kr/category/d7adb89b9e1742a58cf32afdde4a6591?cp=1",
    description: "청명한 겨울 하늘을 연상시키는 은은한 실버블루 컬러웨이. 테일러드 카라와 히든 자석 클로저로 간결함을 극대화했습니다."
  },

  // ==========================================
  // VEST & HOOD
  // ==========================================
  {
    id: "look-23",
    lookNumber: "LOOK 23",
    titleKo: "라벤더 미스트 후드 통밍크 베스트",
    titleEn: "Lavender Mist Hooded Mink Vest",
    categoryKey: "vest-hood",
    categoryLabel: "Vest & Hood",
    peltGrade: "Rare Pastel Lavender Mink (Full Pelt)",
    color: "Lavender Mist",
    image: "assets/images/lookbook/lookbook_05.jpg",
    storeUrl: "https://smartstore.naver.com/goldfur_kr/category/d7adb89b9e1742a58cf32afdde4a6591?cp=1",
    description: "독보적인 분위기를 연출하는 라벤더 파스텔 톤과 넉넉한 후드 실루엣. 코트 안에 이너로 매치하거나 단독 아우터로도 완벽한 럭셔리 베스트입니다."
  },
  {
    id: "look-24",
    lookNumber: "LOOK 24",
    titleKo: "라벤더 후드 베스트 아틀리에 프로필",
    titleEn: "Lavender Hooded Vest Atelier Profile",
    categoryKey: "vest-hood",
    categoryLabel: "Vest & Hood",
    peltGrade: "Rare Pastel Lavender Mink (Full Pelt)",
    color: "Lavender Mist",
    image: "assets/images/lookbook/lookbook_16.jpg",
    storeUrl: "https://smartstore.naver.com/goldfur_kr/category/d7adb89b9e1742a58cf32afdde4a6591?cp=1",
    description: "옆선과 뒷모습까지 빈틈없는 대칭 패턴과 모피 결 맞춤. 부드러운 곡선형 암홀 라인이 다양한 이너웨어와의 완벽한 핏을 보장합니다."
  },
  {
    id: "look-25",
    lookNumber: "LOOK 25",
    titleKo: "실버 애쉬 스탠카라 밍크 베스트",
    titleEn: "Silver Ash Stand Collar Mink Vest",
    categoryKey: "vest-hood",
    categoryLabel: "Vest & Hood",
    peltGrade: "Natural Silver Ash Mink (Full Pelt)",
    color: "Silver Ash",
    image: "assets/images/lookbook/lookbook_17.jpg",
    storeUrl: "https://smartstore.naver.com/goldfur_kr/category/d7adb89b9e1742a58cf32afdde4a6591?cp=1",
    description: "정갈한 스탠드 카라와 군더더기 없는 슬리브리스 라인. 실내외 어디서나 가볍고 편안하게 체온을 유지해 주는 실용적인 아틀리에 마스터피스입니다."
  },
  {
    id: "look-26",
    lookNumber: "LOOK 26",
    titleKo: "토프 케이프렛 반소매 밍크 베스트",
    titleEn: "Taupe Capelet Short-Sleeve Mink Vest",
    categoryKey: "vest-hood",
    categoryLabel: "Vest & Hood",
    peltGrade: "Natural Pastel Mink (Full Pelt)",
    color: "Warm Taupe Gray",
    image: "assets/images/lookbook/lookbook_24.png",
    storeUrl: "https://smartstore.naver.com/goldfur_kr/category/d7adb89b9e1742a58cf32afdde4a6591?cp=1",
    description: "어깨를 부드럽게 감싸는 귀여운 케이프렛 반소매 디자인과 포켓 디테일. 포멀한 정장 팬츠나 데님과 함께 트렌디하게 연출할 수 있습니다."
  },
  {
    id: "look-27",
    lookNumber: "LOOK 27",
    titleKo: "투톤 스탠카라 통밍크 베스트",
    titleEn: "Two-Tone Stand Collar Mink Vest",
    categoryKey: "vest-hood",
    categoryLabel: "Vest & Hood",
    peltGrade: "Two-Tone Natural Mink Combination",
    color: "Espresso & Camel Dual",
    image: "assets/images/lookbook/lookbook_32.jpg",
    storeUrl: "https://smartstore.naver.com/goldfur_kr/category/d7adb89b9e1742a58cf32afdde4a6591?cp=1",
    description: "상하 또는 안팎의 미묘한 톤온톤 배색을 통해 입체감을 더한 스탠카라 베스트. 35년 장인의 정밀 접합 기술로 이음새가 전혀 만져지지 않습니다."
  },
  {
    id: "look-28",
    lookNumber: "LOOK 28",
    titleKo: "리버시블 나파 가죽 후드 무스탕 베스트",
    titleEn: "Reversible Nappa Shearling Hood Vest",
    categoryKey: "vest-hood",
    categoryLabel: "Vest & Hood",
    peltGrade: "Natural Merino Shearling & Nappa Leather",
    color: "Matte Black",
    image: "assets/images/lookbook/lookbook_41.jpg",
    storeUrl: "https://smartstore.naver.com/goldfur_kr/products/12611622393",
    description: "앞면은 매트한 고급 나파 천연 양가죽, 뒷면은 부드러운 양털 시어링으로 양면 착용이 가능한 리버시블 베스트입니다. 실용적인 지퍼 포켓과 지퍼 클로징을 갖췄습니다."
  },
  {
    id: "look-29",
    lookNumber: "LOOK 29",
    titleKo: "듀얼 텍스처 천연 무스탕 베스트",
    titleEn: "Dual Texture Natural Shearling Vest",
    categoryKey: "vest-hood",
    categoryLabel: "Vest & Hood",
    peltGrade: "Natural Spanish Merino Shearling",
    color: "Charcoal Black",
    image: "assets/images/lookbook/lookbook_42.jpg",
    storeUrl: "https://smartstore.naver.com/goldfur_kr/products/12611622393",
    description: "가벼운 착용감의 최고급 메리노 무스탕 원피를 사용해 부피감은 줄이고 보온성은 극대화했습니다. 35년 가죽 특수 봉제 기술의 정수를 보여줍니다."
  },
  {
    id: "look-30",
    lookNumber: "LOOK 30",
    titleKo: "컬리 울 시어링 후드 베스트",
    titleEn: "Curly Wool Shearling Hooded Vest",
    categoryKey: "vest-hood",
    categoryLabel: "Vest & Hood",
    peltGrade: "Full Merino Curly Shearling",
    color: "Noir Velvet Shearling",
    image: "assets/images/lookbook/lookbook_45.jpg",
    storeUrl: "https://smartstore.naver.com/goldfur_kr/products/12611622393",
    description: "천연 양털의 포근한 곱슬거림(Curly)을 그대로 살려 캐주얼하면서도 압도적인 따뜻함을 전하는 후드 베스트. 피부에 닿는 촉감이 극도로 부드럽습니다."
  },

  // ==========================================
  // MUFFLER & ACC
  // ==========================================
  {
    id: "look-31",
    lookNumber: "LOOK 31",
    titleKo: "북미 블랙그라마 크로스 통밍크 머플러",
    titleEn: "North American Blackglama® Cross Muffler",
    categoryKey: "muffler-acc",
    categoryLabel: "Muffler & Acc",
    peltGrade: "North American Blackglama® Full Pelt",
    color: "Pure Black Noir",
    image: "assets/images/lookbook/lookbook_01.png",
    storeUrl: "https://smartstore.naver.com/goldfur_kr/category/d7adb89b9e1742a58cf32afdde4a6591?cp=1",
    description: "단모의 밀도가 가장 빽빽한 북미 블랙그라마 원피로 제작된 시그니처 크로스 머플러. 간편한 홀 삽입형 디자인으로 목선을 정갈하고 포근하게 감싸줍니다."
  },
  {
    id: "look-32",
    lookNumber: "LOOK 32",
    titleKo: "파스텔 블라썸 투톤 크로스 밍크 머플러",
    titleEn: "Pastel Blossom Two-Tone Cross Muffler",
    categoryKey: "muffler-acc",
    categoryLabel: "Muffler & Acc",
    peltGrade: "Natural Pastel Pink & White Mink",
    color: "Soft Blossom & Pure White",
    image: "assets/images/lookbook/lookbook_02.jpg",
    storeUrl: "https://smartstore.naver.com/goldfur_kr/category/d7adb89b9e1742a58cf32afdde4a6591?cp=1",
    description: "로맨틱한 파스텔 핑크와 순백의 화이트가 조화롭게 어우러진 투톤 머플러. 겨울철 코트 룩에 사랑스러운 생기와 따스함을 더해줍니다."
  },
  {
    id: "look-33",
    lookNumber: "LOOK 33",
    titleKo: "골든 팔로미노 크로스 통밍크 머플러",
    titleEn: "Golden Palomino Cross Mink Muffler",
    categoryKey: "muffler-acc",
    categoryLabel: "Muffler & Acc",
    peltGrade: "Rare Palomino Mink (Full Pelt)",
    color: "Warm Palomino Gold",
    image: "assets/images/lookbook/lookbook_03.jpg",
    storeUrl: "https://smartstore.naver.com/goldfur_kr/category/d7adb89b9e1742a58cf32afdde4a6591?cp=1",
    description: "자연이 빚어낸 따뜻한 꿀빛 골드 톤. 블랙이나 카멜, 브라운 계열 아우터에 포인트로 완벽한 고급스러움을 선사합니다."
  },
  {
    id: "look-34",
    lookNumber: "LOOK 34",
    titleKo: "포레스트 세이지 크로스 통밍크 머플러",
    titleEn: "Forest Sage Cross Mink Muffler",
    categoryKey: "muffler-acc",
    categoryLabel: "Muffler & Acc",
    peltGrade: "Custom Toned Full Pelt Mink",
    color: "Deep Forest Sage",
    image: "assets/images/lookbook/lookbook_04.png",
    storeUrl: "https://smartstore.naver.com/goldfur_kr/category/d7adb89b9e1742a58cf32afdde4a6591?cp=1",
    description: "차분하고 기품 있는 짙은 딥 세이지 그린 컬러. 흔하지 않은 독창적인 컬러감으로 나만의 세련된 스타일을 완성할 수 있습니다."
  },
  {
    id: "look-35",
    lookNumber: "LOOK 35",
    titleKo: "사파이어 실버그레이 크로스 밍크 머플러",
    titleEn: "Sapphire Silver Gray Cross Muffler",
    categoryKey: "muffler-acc",
    categoryLabel: "Muffler & Acc",
    peltGrade: "Natural Sapphire Mink (Full Pelt)",
    color: "Sapphire Silver Gray",
    image: "assets/images/lookbook/lookbook_25.png",
    storeUrl: "https://smartstore.naver.com/goldfur_kr/category/d7adb89b9e1742a58cf32afdde4a6591?cp=1",
    description: "천연 사파이어 밍크의 맑고 우아한 실버그레이 톤. 어떤 옷차림에도 자연스럽게 녹아드는 황금모피의 베스트셀러 머플러입니다."
  },
  {
    id: "look-36",
    lookNumber: "LOOK 36",
    titleKo: "딥 마호가니 크로스 통밍크 머플러",
    titleEn: "Deep Mahogany Cross Mink Muffler",
    categoryKey: "muffler-acc",
    categoryLabel: "Muffler & Acc",
    peltGrade: "North American Mahogany Mink",
    color: "Rich Mahogany Brown",
    image: "assets/images/lookbook/lookbook_26.png",
    storeUrl: "https://smartstore.naver.com/goldfur_kr/category/d7adb89b9e1742a58cf32afdde4a6591?cp=1",
    description: "은은한 붉은빛이 감도는 짙은 마호가니 브라운 톤. 35년 부부 장인이 직접 수작업으로 안감 라이닝을 손바느질하여 뒤틀림 없이 목에 밀착됩니다."
  },
  {
    id: "look-37",
    lookNumber: "LOOK 37",
    titleKo: "바이컬러 챠콜 & 펄 밍크 머플러",
    titleEn: "Bicolor Charcoal & Pearl Mink Muffler",
    categoryKey: "muffler-acc",
    categoryLabel: "Muffler & Acc",
    peltGrade: "Two-Tone Full Pelt Combination",
    color: "Charcoal & Pearl Dual",
    image: "assets/images/lookbook/lookbook_27.jpg",
    storeUrl: "https://smartstore.naver.com/goldfur_kr/category/d7adb89b9e1742a58cf32afdde4a6591?cp=1",
    description: "모던한 차콜 그레이와 부드러운 펄 톤의 감각적인 블록 배색. 양면과 크로스 착용 방식에 따라 다양한 분위기를 연출할 수 있습니다."
  },
  {
    id: "look-38",
    lookNumber: "LOOK 38",
    titleKo: "퓨어 펄 화이트 크로스 밍크 머플러",
    titleEn: "Pure Pearl White Cross Muffler",
    categoryKey: "muffler-acc",
    categoryLabel: "Muffler & Acc",
    peltGrade: "Pure White Danish Mink (Full Pelt)",
    color: "Pure Pearl White",
    image: "assets/images/lookbook/lookbook_28.jpg",
    storeUrl: "https://smartstore.naver.com/goldfur_kr/category/d7adb89b9e1742a58cf32afdde4a6591?cp=1",
    description: "눈부신 설원의 순수함을 담은 천연 화이트 밍크. 티끌 하나 없이 깨끗한 최상급 원피만을 선별하여 완성했습니다."
  },
  {
    id: "look-39",
    lookNumber: "LOOK 39",
    titleKo: "내추럴 데미 밍크 크로스 머플러",
    titleEn: "Natural Demi Mink Cross Muffler",
    categoryKey: "muffler-acc",
    categoryLabel: "Muffler & Acc",
    peltGrade: "Natural Demi-Buff Mink (Full Pelt)",
    color: "Natural Brown Demi",
    image: "assets/images/lookbook/lookbook_29.jpg",
    storeUrl: "https://smartstore.naver.com/goldfur_kr/category/d7adb89b9e1742a58cf32afdde4a6591?cp=1",
    description: "원피 고유의 농담(濃淡)이 살아있는 내추럴 브라운 톤. 은은한 광택과 단단한 내구성으로 데일리 머플러로 가장 사랑받는 아이템입니다."
  },
  {
    id: "look-40",
    lookNumber: "LOOK 40",
    titleKo: "웜 샌드 베이지 크로스 머플러",
    titleEn: "Warm Sand Beige Cross Muffler",
    categoryKey: "muffler-acc",
    categoryLabel: "Muffler & Acc",
    peltGrade: "Natural Pastel Mink (Full Pelt)",
    color: "Warm Sand Beige",
    image: "assets/images/lookbook/lookbook_30.jpg",
    storeUrl: "https://smartstore.naver.com/goldfur_kr/category/d7adb89b9e1742a58cf32afdde4a6591?cp=1",
    description: "부드럽고 온화한 샌드 베이지 컬러. 캐시미어 코트나 다운 패딩에 매치해도 가볍고 럭셔리한 포인트를 완성해 줍니다."
  },
  {
    id: "look-41",
    lookNumber: "LOOK 41",
    titleKo: "에스프레소 다크 크로스 머플러",
    titleEn: "Espresso Dark Cross Muffler",
    categoryKey: "muffler-acc",
    categoryLabel: "Muffler & Acc",
    peltGrade: "Premium Dark Mink (Full Pelt)",
    color: "Deep Espresso Brown",
    image: "assets/images/lookbook/lookbook_31.jpg",
    storeUrl: "https://smartstore.naver.com/goldfur_kr/category/d7adb89b9e1742a58cf32afdde4a6591?cp=1",
    description: "차분하면서도 깊은 커피빛 에스프레소 브라운. 어떤 코트와도 무난하게 매치할 수 있는 클래식 아이템입니다."
  },
  {
    id: "look-42",
    lookNumber: "LOOK 42",
    titleKo: "노아 클래식 크로스 밍크 머플러",
    titleEn: "Noir Classic Cross Mink Muffler",
    categoryKey: "muffler-acc",
    categoryLabel: "Muffler & Acc",
    peltGrade: "Full Pelt Female Mink",
    color: "Classic Noir",
    image: "assets/images/lookbook/lookbook_33.jpg",
    storeUrl: "https://smartstore.naver.com/goldfur_kr/category/d7adb89b9e1742a58cf32afdde4a6591?cp=1",
    description: "언제나 정답인 정통 블랙 크로스 머플러. 털 빠짐 방지 특수 마감으로 이너웨어에 털 묻어남을 최소화했습니다."
  },
  {
    id: "look-43",
    lookNumber: "LOOK 43",
    titleKo: "통밍크 돔 버킷햇 아틀리에 모자",
    titleEn: "Full Pelt Mink Dome Bucket Hat",
    categoryKey: "muffler-acc",
    categoryLabel: "Muffler & Acc",
    peltGrade: "Natural Mink Full Pelt",
    color: "Dark Espresso & Black",
    image: "assets/images/lookbook/lookbook_43.png",
    storeUrl: "https://smartstore.naver.com/goldfur_kr/products/12612225559",
    description: "35년 장인의 성형 기법으로 머리 라인을 감싸는 모던한 실루엣의 통밍크 버킷햇. 뛰어난 방한력과 세련된 패션 감각을 동시에 선사합니다."
  }
];
